-- ============================================================================
-- Sistema académico en Supabase
--
-- Traduce las cuatro tablas que hoy viven en el PostgreSQL de SiteGround.
-- Ejecútalo completo en el SQL Editor de Supabase.
--
-- Qué cambia respecto del original y por qué:
--
--   SERIAL          -> bigint generated BY DEFAULT as identity
--                      "by default" en lugar de "always" a propósito: permite
--                      insertar los id originales al importar los CSV y así
--                      conservar las relaciones entre tablas.
--
--   TIMESTAMP       -> timestamptz
--                      El original guardaba hora sin zona. Supabase trabaja en
--                      UTC; con timestamptz las fechas no se corren al leerlas
--                      desde el navegador.
--
--   instructores    -> text[] en vez de integer[]
--                      Apuntaba a usuarios.id de la tabla del panel PHP, que
--                      desaparece. Si la columna trae algo, se conserva como
--                      texto; si está vacía, no estorba.
--
--   curso_base_id   -> sin llave foránea, por ahora
--                      Apuntaba a la tabla `cursos` del sistema PHP. Su
--                      equivalente en Supabase es `courses`, pero hay que
--                      confirmar el tipo de su id antes de enlazarlas. Al final
--                      del archivo queda el ALTER listo, comentado.
--
-- Lo importante de este archivo son las políticas RLS del final. Léelas.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- Función compartida para mantener updated_at
-- ---------------------------------------------------------------------------
create or replace function public.tocar_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


-- ---------------------------------------------------------------------------
-- 1. Respuestas del diagnóstico DISDE
--    Va primero porque estudiantes la referencia.
-- ---------------------------------------------------------------------------
create table if not exists public.diagnostico_disde_respuestas (
    id                     bigint generated by default as identity primary key,
    nombre                 varchar(255) not null,
    correo                 varchar(255) not null,
    grado_academico        varchar(100),
    carrera_licenciatura   varchar(255),
    area_formacion         varchar(255),
    institucion            varchar(255),
    conocimiento_total     integer,          -- sobre 12
    respuestas_area1       jsonb,            -- Programa DISDE
    respuestas_area2       jsonb,            -- Epistemología
    respuestas_area3       jsonb,            -- Metodología
    respuestas_area4       jsonb,            -- Estadística
    respuestas_area5       jsonb,            -- Redacción y APA
    respuestas_area6       jsonb,            -- TIC e IA
    respuestas_completas   jsonb,
    resultados_por_area    jsonb,
    ip_address             varchar(45),      -- ver nota al final sobre esta columna
    user_agent             text,
    email_enviado          boolean default false,
    email_enviado_at       timestamptz,
    created_at             timestamptz default now()
);

create index if not exists idx_diagnostico_correo
    on public.diagnostico_disde_respuestas (correo);
create index if not exists idx_diagnostico_fecha
    on public.diagnostico_disde_respuestas (created_at);
create index if not exists idx_diagnostico_conocimiento
    on public.diagnostico_disde_respuestas (conocimiento_total);

comment on table public.diagnostico_disde_respuestas
    is 'Respuestas del cuestionario diagnóstico DISDE';
comment on column public.diagnostico_disde_respuestas.conocimiento_total
    is 'Puntaje total de preguntas de conocimiento, máximo 12';


-- ---------------------------------------------------------------------------
-- 2. Estudiantes
-- ---------------------------------------------------------------------------
create table if not exists public.estudiantes (
    id                        bigint generated by default as identity primary key,
    nombre                    varchar(255) not null,
    correo                    varchar(255) not null unique,
    foto                      varchar(500),
    matricula                 varchar(100) unique,
    telefono                  varchar(20),
    grado_academico           varchar(100),
    carrera_licenciatura      varchar(255),
    area_formacion            varchar(255),
    institucion_licenciatura  varchar(255),
    institucion_maestria      varchar(255),
    diagnostico_respuesta_id  bigint references public.diagnostico_disde_respuestas (id) on delete set null,
    activo                    boolean default true,
    notas                     text,
    metadata                  jsonb default '{}'::jsonb,
    created_at                timestamptz default now(),
    updated_at                timestamptz default now()
);

create index if not exists idx_estudiantes_correo    on public.estudiantes (correo);
create index if not exists idx_estudiantes_activo    on public.estudiantes (activo);
create index if not exists idx_estudiantes_matricula on public.estudiantes (matricula)
    where matricula is not null;
create index if not exists idx_estudiantes_nombre    on public.estudiantes
    using gin (to_tsvector('spanish', nombre));

drop trigger if exists trg_estudiantes_updated_at on public.estudiantes;
create trigger trg_estudiantes_updated_at
    before update on public.estudiantes
    for each row execute function public.tocar_updated_at();


-- ---------------------------------------------------------------------------
-- 3. Instancias de curso
-- ---------------------------------------------------------------------------
create table if not exists public.cursos_instancias (
    id             bigint generated by default as identity primary key,
    curso_base_id  bigint,                  -- ver ALTER comentado al final
    nombre         varchar(255) not null,   -- "DISDE Propedéutico 2026-A"
    codigo         varchar(50) not null unique,
    descripcion    text,
    fecha_inicio   date not null,
    fecha_fin      date not null,
    periodo        varchar(50),
    cupo_maximo    integer,
    instructores   text[] default '{}',
    estado         varchar(20) default 'activo'
                   check (estado in ('planificado', 'activo', 'finalizado', 'cancelado')),
    metadata       jsonb default '{}'::jsonb,
    created_at     timestamptz default now(),
    updated_at     timestamptz default now()
);

create index if not exists idx_ci_codigo  on public.cursos_instancias (codigo);
create index if not exists idx_ci_estado  on public.cursos_instancias (estado);
create index if not exists idx_ci_periodo on public.cursos_instancias (periodo);
create index if not exists idx_ci_fechas  on public.cursos_instancias (fecha_inicio, fecha_fin);

drop trigger if exists trg_ci_updated_at on public.cursos_instancias;
create trigger trg_ci_updated_at
    before update on public.cursos_instancias
    for each row execute function public.tocar_updated_at();


-- ---------------------------------------------------------------------------
-- 4. Inscripciones
-- ---------------------------------------------------------------------------
create table if not exists public.inscripciones (
    id                   bigint generated by default as identity primary key,
    estudiante_id        bigint not null references public.estudiantes (id) on delete cascade,
    curso_instancia_id   bigint not null references public.cursos_instancias (id) on delete cascade,
    fecha_inscripcion    timestamptz default now(),
    estado               varchar(20) default 'activo'
                         check (estado in ('activo', 'abandonado', 'completado', 'suspendido')),
    calificacion_final   numeric(5, 2),
    aprobado             boolean,
    notas                text,
    metadata             jsonb default '{}'::jsonb,
    created_at           timestamptz default now(),
    updated_at           timestamptz default now(),
    unique (estudiante_id, curso_instancia_id)
);

create index if not exists idx_insc_estudiante   on public.inscripciones (estudiante_id);
create index if not exists idx_insc_curso        on public.inscripciones (curso_instancia_id);
create index if not exists idx_insc_estado       on public.inscripciones (estado);
create index if not exists idx_insc_calificacion on public.inscripciones (calificacion_final)
    where calificacion_final is not null;

drop trigger if exists trg_insc_updated_at on public.inscripciones;
create trigger trg_insc_updated_at
    before update on public.inscripciones
    for each row execute function public.tocar_updated_at();


-- ============================================================================
-- POLÍTICAS RLS
--
-- Esta es la parte que sustituye a api_require_auth() del sistema PHP. Sin
-- ella, con la llave anónima —que es pública y está en el código del sitio—
-- cualquiera podría leer los datos de tus estudiantes.
--
-- La regla es simple:
--   · authenticated  (tú, con sesión iniciada)  -> todo
--   · anon           (cualquier visitante)      -> únicamente INSERTAR una
--                                                  respuesta del diagnóstico
--
-- El rol anónimo NO puede leer ninguna de las cuatro tablas, ni siquiera la
-- del diagnóstico donde sí puede escribir. Puede contestar el cuestionario y
-- no puede ver lo que contestaron los demás.
-- ============================================================================

alter table public.diagnostico_disde_respuestas enable row level security;
alter table public.estudiantes                  enable row level security;
alter table public.cursos_instancias            enable row level security;
alter table public.inscripciones                enable row level security;

-- --- Acceso completo para la sesión autenticada -----------------------------
drop policy if exists admin_todo on public.diagnostico_disde_respuestas;
create policy admin_todo on public.diagnostico_disde_respuestas
    for all to authenticated using (true) with check (true);

drop policy if exists admin_todo on public.estudiantes;
create policy admin_todo on public.estudiantes
    for all to authenticated using (true) with check (true);

drop policy if exists admin_todo on public.cursos_instancias;
create policy admin_todo on public.cursos_instancias
    for all to authenticated using (true) with check (true);

drop policy if exists admin_todo on public.inscripciones;
create policy admin_todo on public.inscripciones
    for all to authenticated using (true) with check (true);

-- --- Única puerta abierta: el formulario público del diagnóstico ------------
-- Solo INSERT. Sin SELECT, sin UPDATE, sin DELETE.
drop policy if exists formulario_publico_inserta on public.diagnostico_disde_respuestas;
create policy formulario_publico_inserta on public.diagnostico_disde_respuestas
    for insert to anon with check (true);


-- ============================================================================
-- PENDIENTES QUE NO PUEDO RESOLVER SIN VERIFICAR EN TU PROYECTO
-- ============================================================================

-- 1. Enlazar cursos_instancias con la tabla courses que ya existe en Supabase.
--    Antes de correrlo, confirma el tipo de courses.id:
--        select column_name, data_type
--        from information_schema.columns
--        where table_name = 'courses' and column_name = 'id';
--    Si es bigint, este ALTER funciona tal cual. Si es uuid, hay que cambiar
--    primero el tipo de curso_base_id.
--
-- alter table public.cursos_instancias
--     add constraint fk_curso_base
--     foreign key (curso_base_id) references public.courses (id) on delete set null;

-- 2. ip_address y user_agent del diagnóstico.
--    Las llenaba PHP desde el servidor. Un navegador no conoce su propia IP,
--    así que si el formulario escribe directo a Supabase, esas dos columnas se
--    quedan vacías. Se conservan para no perder lo ya registrado. Si te
--    interesa seguir capturándolas, tiene que hacerlo una Edge Function.

-- 3. El correo de bienvenida.
--    El controlador PHP enviaba un correo con plantilla HTML y enlace a la
--    página de bienvenida, y marcaba email_enviado. Supabase desde el navegador
--    no envía correo. Las columnas se conservan, pero el envío hay que
--    reconstruirlo con una Edge Function antes de apagar el PHP, o el
--    estudiante dejará de recibirlo sin que nadie se entere.
