-- ============================================================================
-- Diagnóstico inicial del Seminario de Investigación Teórico (DISDE, 2026-2)
--
-- CÓRRELO DESPUÉS DE 00_roles.sql. Las políticas del final usan tiene_rol().
-- No depende de 01_academico.sql: puede correrse antes o después.
--
-- De dónde sale este diseño:
--   BACKEND.md proponía dos tablas —la respuesta completa y el desglose de las
--   escalas numéricas— con un endpoint PHP en medio. Las dos tablas se
--   conservan porque la idea es buena: sacar promedios de un JSON es incómodo
--   y lento. Lo que cambia es el resto, para que encaje con lo que ya tienes:
--
--     PHP en hosting compartido  ->  Supabase, como el resto del sitio
--     endpoint que valida        ->  función guardar_diagnostico_seminario()
--     tabla abierta al público   ->  ninguna política para anon
--
--   El formulario no escribe en las tablas. Llama a la función, y la función
--   es la única que escribe. Así el visitante puede contestar sin que la
--   llave anónima —que está a la vista en el código del sitio— sirva para
--   leer, modificar ni borrar nada.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- Utilidad: convertir un valor JSON en text[]
--
-- Los grupos de casillas llegan como arreglo, pero si el navegador manda una
-- sola marca puede llegar como cadena suelta. Esto normaliza los dos casos y
-- el nulo.
-- ---------------------------------------------------------------------------
create or replace function public.jsonb_a_texto_array(j jsonb)
returns text[]
language sql
immutable
as $$
    select case
        when j is null or jsonb_typeof(j) = 'null'  then '{}'::text[]
        when jsonb_typeof(j) = 'array'              then array(select jsonb_array_elements_text(j))
        else array[j #>> '{}']
    end;
$$;


-- ---------------------------------------------------------------------------
-- 1. La respuesta
--
-- Se promueven a columna los datos que se usan para listar, filtrar y ordenar.
-- Todo lo demás —los textos largos, los arreglos de casillas, las escalas—
-- vive íntegro en payload. Ninguna respuesta se pierde por no tener columna.
-- ---------------------------------------------------------------------------
create table if not exists public.seminario_diagnostico (
    id                bigint generated by default as identity primary key,
    ciclo             text not null,
    curso             text not null,
    nombre            text not null,
    correo            text not null,
    telefono          text,
    generacion        text,
    dedicacion        text,
    horas_semana      smallint check (horas_semana between 0 and 80),
    licenciatura_area text,
    maestria_area     text,
    director          text,
    titulo            text,
    pregunta_central  text,
    enfoque           text,
    ia_frecuencia     text,
    nps               smallint check (nps between 0 and 10),
    consentimiento    boolean not null default false,
    payload           jsonb not null default '{}'::jsonb,
    navegador         text,
    envios            integer not null default 1,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now(),
    unique (ciclo, correo)
);

create index if not exists idx_sd_ciclo   on public.seminario_diagnostico (ciclo);
create index if not exists idx_sd_fecha   on public.seminario_diagnostico (created_at desc);
create index if not exists idx_sd_correo  on public.seminario_diagnostico (correo);
create index if not exists idx_sd_payload on public.seminario_diagnostico using gin (payload);

comment on table public.seminario_diagnostico
    is 'Respuestas del diagnóstico inicial del seminario. Una por alumno y ciclo.';
comment on column public.seminario_diagnostico.payload
    is 'La respuesta íntegra tal como la mandó el formulario, incluidos los campos sin columna propia.';
comment on column public.seminario_diagnostico.envios
    is 'Cuántas veces se ha guardado esta respuesta. Mayor que 1 significa que el alumno la corrigió.';


-- ---------------------------------------------------------------------------
-- 2. El desglose de las escalas numéricas
--
-- Tres matrices del formulario: avance por componente (0 a 4), autodiagnóstico
-- de competencias (1 a 5) y satisfacción con el programa (1 a 5). Aquí cada
-- casilla es una fila, que es lo que permite sacar promedios por reactivo sin
-- pelearse con el JSON.
--
-- La llena la función a partir del payload. No se escribe a mano.
-- ---------------------------------------------------------------------------
create table if not exists public.seminario_diagnostico_item (
    respuesta_id  bigint   not null references public.seminario_diagnostico (id) on delete cascade,
    grupo         text     not null check (grupo in ('avance', 'competencia', 'satisfaccion')),
    clave         text     not null,
    valor         smallint not null check (valor between 0 and 10),
    primary key (respuesta_id, clave)
);

create index if not exists idx_sdi_grupo on public.seminario_diagnostico_item (grupo, clave);


-- ---------------------------------------------------------------------------
-- 3. Etiquetas de los reactivos
--
-- El formulario manda claves ('comp_apa'), no textos. Sin esto, las consultas
-- y el panel mostrarían claves crudas. Va en tabla y no en el código del panel
-- para que el día que cambie un reactivo se corrija en un solo lugar.
-- ---------------------------------------------------------------------------
create table if not exists public.seminario_diagnostico_reactivo (
    clave     text primary key,
    grupo     text not null check (grupo in ('avance', 'competencia', 'satisfaccion')),
    etiqueta  text not null,
    orden     smallint not null default 0
);

insert into public.seminario_diagnostico_reactivo (clave, grupo, etiqueta, orden) values
    ('cap1_contexto',       'avance', 'Contextualización del problema',                1),
    ('cap1_planteamiento',  'avance', 'Planteamiento y preguntas de investigación',    2),
    ('cap1_objetivos',      'avance', 'Objetivos general y específicos',               3),
    ('cap1_hipotesis',      'avance', 'Hipótesis o supuestos',                         4),
    ('cap1_justificacion',  'avance', 'Justificación y delimitación',                  5),
    ('cap2_estado',         'avance', 'Estado del arte',                               6),
    ('cap2_teorica',        'avance', 'Marco teórico: teoría base',                    7),
    ('cap2_conceptual',     'avance', 'Marco conceptual',                              8),
    ('cap3_metodo',         'avance', 'Decisiones metodológicas',                      9),
    ('cap3_instrumento',    'avance', 'Diseño del instrumento',                       10),

    ('comp_busqueda',    'competencia', 'Diseñar una ecuación de búsqueda en Scopus o Web of Science',  1),
    ('comp_lectura',     'competencia', 'Leer críticamente un artículo científico en inglés',           2),
    ('comp_distincion',  'competencia', 'Distinguir marco teórico de marco conceptual',                 3),
    ('comp_seleccion',   'competencia', 'Justificar por qué elegí una teoría y no otra',                4),
    ('comp_brecha',      'competencia', 'Identificar y argumentar una brecha en el conocimiento',       5),
    ('comp_matriz',      'competencia', 'Construir una matriz de congruencia',                          6),
    ('comp_operacion',   'competencia', 'Operacionalizar un concepto en variables o categorías',        7),
    ('comp_sintesis',    'competencia', 'Sintetizar veinte fuentes en un argumento propio',             8),
    ('comp_redaccion',   'competencia', 'Redactar en estilo académico impersonal',                      9),
    ('comp_apa',         'competencia', 'Aplicar normas APA 7 sin consultar a cada rato',              10),
    ('comp_software',    'competencia', 'Usar software de análisis cualitativo o bibliométrico',       11),

    ('sat_programa',       'satisfaccion', 'El programa doctoral en su conjunto',            1),
    ('sat_materias',       'satisfaccion', 'Las unidades de aprendizaje cursadas',           2),
    ('sat_director',       'satisfaccion', 'El acompañamiento de mi director de tesis',      3),
    ('sat_coloquios',      'satisfaccion', 'Los coloquios de investigación',                 4),
    ('sat_biblio',         'satisfaccion', 'El acceso a bases de datos y bibliografía',      5),
    ('sat_coordinacion',   'satisfaccion', 'La comunicación de la Coordinación',             6),
    ('sat_instalaciones',  'satisfaccion', 'Instalaciones y recursos tecnológicos',          7),
    ('sat_pares',          'satisfaccion', 'La convivencia y el trabajo con mis compañeros', 8)
on conflict (clave) do update
    set grupo = excluded.grupo, etiqueta = excluded.etiqueta, orden = excluded.orden;


-- ---------------------------------------------------------------------------
-- 4. La única puerta de entrada
--
-- SECURITY DEFINER: corre con los permisos del dueño, así que puede escribir
-- aunque el visitante no tenga ninguna política a su favor. Es lo que permite
-- que las tablas queden completamente cerradas a anon.
--
-- Qué hace, en orden:
--   1. Valida nombre, correo y consentimiento. Sin los tres, no guarda.
--   2. Inserta o actualiza la respuesta, según (ciclo, correo).
--   3. Rehace el desglose de las tres matrices a partir del payload.
--
-- Sobre el upsert: si alguien vuelve a contestar con el mismo correo, la
-- respuesta se reemplaza y envios sube en uno. Es a propósito, para que un
-- alumno pueda corregirse. La contrapartida es que quien conozca el correo de
-- un compañero podría sobrescribir su respuesta; con un grupo de doctorado el
-- riesgo es asumible y a cambio nadie puede LEER lo que contestó nadie.
-- ---------------------------------------------------------------------------
create or replace function public.guardar_diagnostico_seminario(datos jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_ciclo   text;
    v_curso   text;
    v_nombre  text;
    v_correo  text;
    v_id      bigint;
    v_previo  integer;
begin
    if datos is null or jsonb_typeof(datos) <> 'object' then
        raise exception 'La respuesta no tiene el formato esperado.' using errcode = '22023';
    end if;

    -- Tope de tamaño. Sin esto, la puerta abierta al público es también una
    -- puerta para llenar la base con basura.
    if pg_column_size(datos) > 60000 then
        raise exception 'La respuesta es demasiado grande.' using errcode = '22023';
    end if;

    v_ciclo  := coalesce(nullif(btrim(datos -> '_meta' ->> 'ciclo'), ''), '2026-2');
    v_curso  := coalesce(nullif(btrim(datos -> '_meta' ->> 'curso'), ''), 'Seminario de Investigación Teórico');
    v_nombre := nullif(btrim(datos ->> 'nombre'), '');
    v_correo := lower(nullif(btrim(datos ->> 'correo'), ''));

    if v_nombre is null then
        raise exception 'Falta el nombre.' using errcode = '22023';
    end if;
    if v_correo is null or v_correo !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
        raise exception 'El correo no es válido.' using errcode = '22023';
    end if;
    if nullif(btrim(datos ->> 'consentimiento'), '') is null then
        raise exception 'Falta el consentimiento.' using errcode = '22023';
    end if;

    select sd.envios into v_previo
    from public.seminario_diagnostico sd
    where sd.ciclo = v_ciclo and sd.correo = v_correo;

    insert into public.seminario_diagnostico (
        ciclo, curso, nombre, correo, telefono, generacion, dedicacion,
        horas_semana, licenciatura_area, maestria_area, director, titulo,
        pregunta_central, enfoque, ia_frecuencia, nps, consentimiento,
        payload, navegador
    )
    values (
        v_ciclo,
        v_curso,
        v_nombre,
        v_correo,
        nullif(btrim(datos ->> 'telefono'), ''),
        nullif(btrim(datos ->> 'generacion'), ''),
        nullif(btrim(datos ->> 'dedicacion'), ''),
        case when datos ->> 'horas_semana' ~ '^[0-9]{1,2}$'
             then least((datos ->> 'horas_semana')::smallint, 80::smallint) end,
        nullif(btrim(datos ->> 'licenciatura_area'), ''),
        nullif(btrim(datos ->> 'maestria_area'), ''),
        nullif(btrim(datos ->> 'director'), ''),
        nullif(btrim(datos ->> 'titulo'), ''),
        nullif(btrim(datos ->> 'pregunta_central'), ''),
        nullif(btrim(datos ->> 'enfoque'), ''),
        nullif(btrim(datos ->> 'ia_frecuencia'), ''),
        case when datos ->> 'nps' ~ '^(10|[0-9])$' then (datos ->> 'nps')::smallint end,
        true,
        datos - '_meta',
        left(coalesce(datos -> '_meta' ->> 'navegador', ''), 400)
    )
    on conflict (ciclo, correo) do update set
        curso             = excluded.curso,
        nombre            = excluded.nombre,
        telefono          = excluded.telefono,
        generacion        = excluded.generacion,
        dedicacion        = excluded.dedicacion,
        horas_semana      = excluded.horas_semana,
        licenciatura_area = excluded.licenciatura_area,
        maestria_area     = excluded.maestria_area,
        director          = excluded.director,
        titulo            = excluded.titulo,
        pregunta_central  = excluded.pregunta_central,
        enfoque           = excluded.enfoque,
        ia_frecuencia     = excluded.ia_frecuencia,
        nps               = excluded.nps,
        payload           = excluded.payload,
        navegador         = excluded.navegador,
        envios            = seminario_diagnostico.envios + 1,
        updated_at        = now()
    returning id into v_id;

    -- Rehacer el desglose. Se borra y se vuelve a insertar porque una
    -- corrección puede haber dejado en blanco un reactivo que antes tenía
    -- valor, y un upsert por clave dejaría el valor viejo colgado.
    delete from public.seminario_diagnostico_item where respuesta_id = v_id;

    insert into public.seminario_diagnostico_item (respuesta_id, grupo, clave, valor)
    select v_id,
           case
               when e.key ~ '^cap[0-9]+_'  then 'avance'
               when e.key ~ '^comp_'       then 'competencia'
               when e.key ~ '^sat_'        then 'satisfaccion'
           end,
           e.key,
           e.value::smallint
    from jsonb_each_text(datos) e
    where e.key ~ '^(cap[0-9]+|comp|sat)_'
      and e.value ~ '^[0-9]$';

    return jsonb_build_object(
        'ok',     true,
        'id',     v_id,
        'nuevo',  v_previo is null,
        'envios', coalesce(v_previo, 0) + 1
    );
end;
$$;

comment on function public.guardar_diagnostico_seminario(jsonb)
    is 'Guarda una respuesta del diagnóstico del seminario. Es la única vía de escritura desde el sitio.';

revoke all on function public.guardar_diagnostico_seminario(jsonb) from public;
grant execute on function public.guardar_diagnostico_seminario(jsonb) to anon, authenticated;


-- ---------------------------------------------------------------------------
-- 5. Vistas de lectura para el panel y para el SQL Editor
--
-- security_invoker = true no es un detalle: sin él, una vista corre con los
-- permisos de quien la creó y se salta el RLS de las tablas que consulta.
-- Como PostgREST publica las vistas, eso dejaría los datos de los alumnos al
-- alcance de la llave anónima. Con security_invoker, la vista respeta las
-- políticas de abajo: admin ve, los demás no ven nada.
-- ---------------------------------------------------------------------------

-- Promedio por reactivo. Lo primero que se quiere ver: dónde está parado el
-- grupo, componente por componente, con lo más atrasado arriba.
create or replace view public.v_seminario_reactivos
with (security_invoker = true) as
select r.ciclo,
       i.grupo,
       i.clave,
       coalesce(x.etiqueta, i.clave)                      as etiqueta,
       coalesce(x.orden, 99)                              as orden,
       round(avg(i.valor)::numeric, 2)                    as promedio,
       count(*)                                           as n,
       count(*) filter (where i.valor = 0)                as en_cero,
       count(*) filter (where i.valor >= 3)               as tres_o_mas,
       min(i.valor)                                       as minimo,
       max(i.valor)                                       as maximo
from public.seminario_diagnostico_item i
join public.seminario_diagnostico r on r.id = i.respuesta_id
left join public.seminario_diagnostico_reactivo x on x.clave = i.clave
group by r.ciclo, i.grupo, i.clave, x.etiqueta, x.orden;

-- Una fila por alumno con sus tres promedios. Sirve para detectar de un
-- vistazo a quién hay que citar a asesoría desde la primera semana.
create or replace view public.v_seminario_alumnos
with (security_invoker = true) as
select r.id,
       r.ciclo,
       r.nombre,
       r.correo,
       r.dedicacion,
       r.horas_semana,
       r.enfoque,
       r.ia_frecuencia,
       r.nps,
       r.envios,
       r.created_at,
       round(avg(i.valor) filter (where i.grupo = 'avance')::numeric, 2)       as avance,
       round(avg(i.valor) filter (where i.grupo = 'competencia')::numeric, 2)  as competencia,
       round(avg(i.valor) filter (where i.grupo = 'satisfaccion')::numeric, 2) as satisfaccion
from public.seminario_diagnostico r
left join public.seminario_diagnostico_item i on i.respuesta_id = r.id
group by r.id;


-- ============================================================================
-- POLÍTICAS RLS
--
-- admin   todo, en las tres tablas.
-- editor  nada. Quien ayude con el blog no tiene por qué ver correos,
--         teléfonos ni lo que cada alumno contestó sobre su director de tesis.
-- anon    nada, ni siquiera insertar. Escribe la función, no el visitante.
--
-- Fíjate en la diferencia con diagnostico_disde_respuestas, que sí tiene una
-- política de INSERT para anon: ahí el formulario escribe directo en la tabla.
-- Aquí no hace falta, y una puerta que no existe no se puede forzar.
-- ============================================================================

alter table public.seminario_diagnostico             enable row level security;
alter table public.seminario_diagnostico_item        enable row level security;
alter table public.seminario_diagnostico_reactivo    enable row level security;

drop policy if exists admin_todo on public.seminario_diagnostico;
create policy admin_todo on public.seminario_diagnostico
    for all to authenticated
    using (public.tiene_rol('admin'))
    with check (public.tiene_rol('admin'));

drop policy if exists admin_todo on public.seminario_diagnostico_item;
create policy admin_todo on public.seminario_diagnostico_item
    for all to authenticated
    using (public.tiene_rol('admin'))
    with check (public.tiene_rol('admin'));

drop policy if exists admin_todo on public.seminario_diagnostico_reactivo;
create policy admin_todo on public.seminario_diagnostico_reactivo
    for all to authenticated
    using (public.tiene_rol('admin'))
    with check (public.tiene_rol('admin'));

-- Las etiquetas no son un dato sensible, pero tampoco hacen falta fuera del
-- panel: quien tiene sesión puede leerlas, el visitante no.
drop policy if exists reactivos_lectura on public.seminario_diagnostico_reactivo;
create policy reactivos_lectura on public.seminario_diagnostico_reactivo
    for select to authenticated using (true);

revoke all on table public.seminario_diagnostico          from anon;
revoke all on table public.seminario_diagnostico_item     from anon;
revoke all on table public.seminario_diagnostico_reactivo from anon;
revoke all on table public.v_seminario_reactivos          from anon;
revoke all on table public.v_seminario_alumnos            from anon;

grant select on public.v_seminario_reactivos to authenticated;
grant select on public.v_seminario_alumnos   to authenticated;


-- ============================================================================
-- CÓMO COMPROBAR QUE QUEDÓ BIEN
--
-- 1. Que la función existe y valida:
--        select public.guardar_diagnostico_seminario('{"nombre":"x"}'::jsonb);
--    Debe fallar con «El correo no es válido».
--
-- 2. Que las tablas están cerradas a anon. En el SQL Editor:
--        select rolname from pg_roles where rolname = 'anon';
--        -- y luego, con la llave anónima desde el navegador, un select a
--        -- seminario_diagnostico debe devolver cero filas, nunca datos.
--
-- 3. Después de la primera respuesta real:
--        select * from public.v_seminario_reactivos
--        where grupo = 'avance' order by promedio;
--
-- 4. Obstáculos declarados, que viven en el payload:
--        select obstaculo, count(*) as menciones
--        from public.seminario_diagnostico r,
--             jsonb_array_elements_text(r.payload -> 'obstaculo') as obstaculo
--        where r.ciclo = '2026-2'
--        group by obstaculo order by menciones desc;
--
-- 5. NPS del programa:
--        select round(100.0 * (
--                 count(*) filter (where nps >= 9) - count(*) filter (where nps <= 6)
--               ) / nullif(count(*), 0), 1) as nps
--        from public.seminario_diagnostico
--        where ciclo = '2026-2' and nps is not null;
-- ============================================================================
